-- SQLite
CREATE TABLE restaurants(res_id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, city TEXT NOT NULL, AREA TEXT NOT NULL, menu_id TEXT NOT NULL )

SELECT * FROM orders;
SELECT * FROM user;
SELECT * FROM restaurant;



DELETE 